Month8 redux
anastasiian3/react-burger pull request #2
Opened 2022-11-08 18:22 UTC by anastasiian3

2022-11-08 19:40 UTC, randomroot requested changes
**Доброго времени суток!**

Вы проделали **очень хорошую** работу по добавлению редакса и DnD в ваш проект, применили **удобную** библиотеку для отслеживания скролла в списке ингредиентов, выстроили правильную **файловую структуру**, разделив экшены и редьюсеры по сущностям, производите **сброс состояния** после выполнения заказа, так держать 👍 

Тем не менее, для успешной сдачи работы, вам необходимо внимательно изучить комментарии к вашему коду, указанные в рамках ревью и провести **исправления** согласно выявленным недостаткам, обратив особое внимание на:

- Следует скорректировать некоторые `PropTypes` в новых и старых компонентах (часть пропсов не были описаны);
- Происходит множественный вызов запроса на получения ингредиента с сервера по причина триггера `useEffect` в каждой из категории ингредиентов;
- В работе присутствует дублирование кода, отвечающего за рендер компонентов, отличающегося в 1-2 пропсах с использование тернарного оператора (см. компонент `burger-constructor.jsx`). Следует отказаться от такого подхода и перенести логику из него непосредственно в сами логические пропсы (подробнее в комментариях);

Также, в рамках работы были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу. Обратите внимание на момент с вычислением счётчиков у ингредиентов.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**.

---

**Успешного вам рефакторинга и хорошего настроения!** 🐈

2022-11-08 19:40 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +  const ingredientsId = ingredients.map((ingredient) => ingredient._id);
🟡 **Можно улучшить:**

Не целесообразно генерировать массив ингредиентов для отправки при каждом рендере, создавайте массив непосредственно при отправке данных из функции `openOrderModal`. Аналогично ниже с `userOrder`

2022-11-08 19:40 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    dispatch({ type: RESET_CONSTRUCTOR_INGREDIENTS });
🟢 **Отлично:**

Очень хорошо, что сбрасываете состояние заказа после закрытия окна 👍

2022-11-08 19:40 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +              style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2022-11-08 19:40 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +        ) : (
🔴 **Нужно исправить:**

Не следует дублировать описание рендера кнопки, т.к. по факту оно отличается только в наличии пропса `disabled`. Следует отказаться от тернарного оператора и перенести условие непосредственно в пропс `disabled={...}`

2022-11-08 19:40 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const [bunRef, inViewBun] = useInView(options);
🟢 **Отлично:**

Плюс за использование проверенной библиотеки для решения задачи со скроллом 👍

2022-11-08 19:40 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
>    const [current, setCurrent] = useState('bun');
🟡 **Можно улучшить:**

Имеет смысл в данном стейте также использовать константу `INGREDIENTS`

2022-11-08 19:40 UTC, randomroot commented on src/components/constructor-card/constructor-card.jsx
> +export default ConstructorCard;
🔴 **Нужно исправить:**

Т.к. у данного компонента есть пропсы, то следует прописать его `PropTypes`

2022-11-08 19:40 UTC, randomroot commented on src/components/ingredient-card/ingredient-card.jsx
> +    });
🟡 **Можно улучшить:**

Подсчёт кол-ва элементов, добавленных в конструктор осуществляется правильно, однако не совсем оптимально, по причине того, что для каждого ингредиента осуществляется полный проход по всему массиву ингредиентов в поиске совпадающих. Если считать, что длина массива = N, то сложность данного алгоритма в целом для всех элементов = O(N*N), что при большом количестве элементов может ухудшать производительность вашего проекта.

Для оптимизации данного процесса имеет смысл рассмотреть альтернативный путь подсчёта, например проводить его в сторе, храня значения счётчиков там в отдельном объекте и изменяя его показатели при каждом добавлении/удалении элемента. Таким образом, вычислительная сложность уменьшается до O(1), т.к. сложность процесса вычисления не будет зависеть от размера массива.

О вычислительной сложности можно прочитать например здесь: https://tproger.ru/articles/computational-complexity-explained/

2022-11-08 19:40 UTC, randomroot commented on src/components/ingredients-category/ingredients-category.jsx
> +    dispatch(getIngredients());
🔴 **Нужно исправить:**

Вызов функции получения ингредиентов из API следует вынести в `App.tsx`, т.к. ингредиенты необходимо получить для всего приложения сразу. В текущей реализации вы вызываете данный метод для каждой из трех категорий ингредиентов, что приводит к множественным запросам (https://disk.yandex.ru/i/wr91UGFi_PXquA)

2022-11-08 19:40 UTC, randomroot commented on src/components/ingredients-category/ingredients-category.jsx
>  };
🔴 **Нужно исправить:**

В данном PropTypes:

1) Нет описание пропса `title`;
2) Обязательные параметры следует указывать вместе с `isRequired`

2022-11-08 19:40 UTC, randomroot commented on src/services/actions/burger-ingredients.js
> +    });
🔴 **Нужно исправить:**

При выполнении API запросов следует также добавлять в цепочку блок `catch`, который будет вызван в случае возникновения ошибок еще до попадания на сервер, например сбой в работе `fetch`, отсутствие сети и т.п. ситуации. А в этом блоке следует вызывать `dispatch` с соответствующим типом ошибки

2022-11-08 19:40 UTC, randomroot commented on src/services/actions/order-details.js
> +        console.log(error);
🟡 **Можно улучшить:**

Логгирование в консоль следует минимизировать, однако если требуется вывод ошибок, то лучше использовать `console.error` - он добавит сообщения в соответствующий стек ошибок и будет проще отслеживать их

2022-11-08 19:40 UTC, randomroot commented on src/services/reducers/burger-constructor.js
> +        ingredients: [...state.ingredients].filter((ingredient) => ingredient.key !== action.key),
🟡 **Можно улучшить:**

Функция `filter` возвращает новый массив в результате своей работы, поэтому не целесообразно дополнительно создавать копию `state.ingredients` вручную

2022-11-08 19:40 UTC, randomroot commented on src/services/reducers/burger-ingredients.js
> +  ingredient: {},
🟡 **Можно улучшить:**

Значение по-умолчанию которое может быть пустым целесообразно задавать с помощью `null` или `undefined`, чтобы обеспечить необходимость в проверках на пустоту непосредственно в том компоненте, где оно используется. Это поможет исключить случайные ошибки при обращении к пустому объекту без ключей (в том числе когда есть вложенные значения)

2022-11-08 19:40 UTC, randomroot commented on package.json
> +    "@reduxjs/toolkit": "^1.9.0",
🟡 **Можно улучшить:**

Т.к. в рамках вашего проекта данная библиотека не используется, то следует удалить её из зависимостей, чтобы сэкономить место на диске :)

2022-11-11 11:00 UTC, anastasiian3 commented on package.json
> +    "@reduxjs/toolkit": "^1.9.0",
Добрый день! Тогда не будет работать combineReducers

2022-11-11 11:37 UTC, randomroot commented on package.json
> +    "@reduxjs/toolkit": "^1.9.0",
Можно воспользоваться другим импортом:
`import { combineReducers } from 'redux'`

2022-11-11 11:48 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, так держать👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-12-02 18:31 UTC, merged